# Generated by Django 5.1.1 on 2024-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_post',
            name='picture',
            field=models.ImageField(default='img/default.jpeg', upload_to='static/img/news_pic/'),
        ),
    ]
